### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by omrsfylmz** [Gdsc-Lbce/GDSC_LBCE_Website#17]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

The readme file is included unnecessary parts which are 

```
cd client
npm i 

npm start
```

* **What is the expected behavior?**
I can fix this typo

**Comment by Gdsc-Lbce** [comment]
Okay go ahead @omrsfylmz
