### ISSUE TITLE
Update the Readme file for the Repository 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Gdsc-Lbce/GDSC_LBCE_Website#23]
Hey @ashish-ad since we are in the phase where first we are looking for the workflow of the website and various figma designs, I am thinking of changing the readme file of the repository which includes :-

- Setup and contributions guidelines to follow to contribute to the repository. 
- About the repository and the community. 
- Change of logo from HacktoberFest to GDSC LBCE logo.
- Adding of the contributors.
- Contributor's Code of Conduct. 

If you think the issue is useful for the community and to the Repository I would like to request you to assign the issue to me under WoC.

**Comment by ashish-ad** [comment]
Yeah sure!

**Comment by Vedant-Jayesh-Oza** [comment]
Okay @ashish-ad Sir, can you assign the issue to me

**Comment by ashish-ad** [comment]
I have assigned this u can work upon this. @Vedant-Jayesh-Oza
