### ISSUE TITLE
Improvise and Change the Footer of the Website. 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Gdsc-Lbce/GDSC_LBCE_Website#26]
Hey @ashish-ad Sir, I am planning to improvise and do some changes to the Footer of the Website. Please Assign me this issue.

**Comment by ashish-ad** [comment]
Hey @Vedant-Jayesh-Oza, Can I assign this someone else as u are dealing with one of the issues.

**Comment by Vedant-Jayesh-Oza** [comment]
Yeah like I don't have any problem working with 2 issues but if you want to assign the issue to someone else that would also be great 💯

**Comment by Vedant-Jayesh-Oza** [comment]
You can assign it to someone else too that would be great 💯

**Comment by harshita214** [comment]
I would like to work on it

**Comment by dee-ksha** [comment]
Please assign me this issue, I'd like to work on it

**Comment by ashish-ad** [comment]
Ok, U both have to collaborate with this issue @dee-ksha and @harshita214.
and do collaborate with other team members so that ur code shouldn't be conflicting or breaking when merged.
