### ISSUE TITLE
Change the Navbar of the Website and Add the GDSC LBCE logo to the Navbar.  

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Gdsc-Lbce/GDSC_LBCE_Website#27]
Hey @ashish-ad Sir, I am planning to change the Navbar of the Website and to add the GDSC LBCE Logo to the Website. Please Assign this issue to me. Thank You.

**Comment by ashish-ad** [comment]
Good to go u can start working on this!
But do collaborate with the team.

**Comment by ashish-ad** [comment]
Hey @Vedant-Jayesh-Oza, do this issue needs more development if no then u may close this issue.

**Comment by Vedant-Jayesh-Oza** [comment]
No more development required in this issue, you may close it.
