### ISSUE TITLE
FAQ SECTION

### ISSUE THREAD

**Issue by shahdhairya51** [Gdsc-Lbce/GDSC_LBCE_Website#28]
* **I'm submitting a ...**

  - [x] feature request
 

* **Do you want to request a *feature* or report a *bug*?**
i want to request a feature

* **What is the current behavior?**
at present this website has no FAQ section so for all small doubts participants will have to contact the organizers.

* **What is the expected behavior?**
i am planning to make FAQ section that would clear all basic doubts regarding the organization, so @ashish-ad  sir if u feel that this would be helpful to the community so plz assign this issue to me.
![faq](https://user-images.githubusercontent.com/89531928/145704781-fcb4b251-6044-4066-acdd-e28247b2bbf3.jpg)

**Comment by ashish-ad** [comment]
Good to go u can start working on this!
And do collaborate with the team.
Get familiar with React.js.

**Comment by ashish-ad** [comment]
Hey @shahdhairya51, as I can see that @jay-io has changed ur code of FAQ section, so @shahdhairya51 you have to work on this again. and please try to keep the main App.js clean and try making ur FAQ section inside the component file and then import the file as a component and then the try including that in main App.js file.

**Comment by ashish-ad** [comment]
U can collaborate with @jay-io to get an idea of how to do that.
