### ISSUE TITLE
Banner for the website

### ISSUE THREAD

**Issue by jay-io** [Gdsc-Lbce/GDSC_LBCE_Website#31]
* **I'm submitting a ...**
  - [x] feature request

* **What is the current behaviour?**
The dummy page is currently lacking a banner.

* **What is the expected behaviour?**
The web app will feature a welcome banner that will contain the name of the college and a few aesthetic elements.
![Figma screenshot](https://user-images.githubusercontent.com/55305804/145843187-df98dd2d-0cb7-48d2-97d0-cee71d8bc206.png)

**Comment by ivoryhat** [comment]
I'd like to work on this.

**Comment by ashish-ad** [comment]
Hey @jay-io, I u may close this issue.
