### ISSUE TITLE
About Us section for the website

### ISSUE THREAD

**Issue by jay-io** [Gdsc-Lbce/GDSC_LBCE_Website#32]
* **I'm submitting a ...**
  
  - [x] feature request

* **What is the current behavior?**
There is a small About-us section in the website currently with no styling.

* **What is the expected behaviour?**
There should be an about-us similar to what's been shown below.
![Screenshot from 2021-12-13 21-28-10](https://user-images.githubusercontent.com/55305804/145845312-a06e90c5-9694-4c3c-9a50-5293c8ec63c6.png)

**Comment by ashish-ad** [comment]
Good to go u can start working on this!
And do collaborate with the team.

**Comment by ashish-ad** [comment]
U may close this issue @jay-io.
