### ISSUE TITLE
Creating a blog page and UI design.

### ISSUE THREAD

**Issue by ashish-ad** [Gdsc-Lbce/GDSC_LBCE_Website#33]
* **I'm submitting a feature request**
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**

Adding a different page for the blog.
Request for UI design.

* **What is the current behaviour?**

Current UI design doesn't have a UI design

* **What is the expected behaviour?**

**Comment by harshita214** [comment]
I would like to work on the frontend part of the blog page

**Comment by ashish-ad** [comment]
Hey @harshita214, are u doing any progress in this issue.

**Comment by harshita214** [comment]
Yes yes, I am creating it.
