### ISSUE TITLE
Add a splash loader

### ISSUE THREAD

**Issue by jay-io** [Gdsc-Lbce/GDSC_LBCE_Website#35]
* **I'm submitting a ...**
  
  - [x] feature request

* **What is the current behavior?**
The current website design has no splash greeter.

* **What is the expected behaviour?**
The website will feature a splash greeter.

* **Example: (Google Workspace)**
https://storage.googleapis.com/support-forums-api/attachment/thread-115389767-7860076060655447775.png

**Comment by jay-io** [comment]
Just had this new idea. Someone who needs more issues to work with could try working it out, or I might take it up after my first two PRs.

**Comment by sabyasachi-894** [comment]
I can try to work it out ...

**Comment by Vedant-Jayesh-Oza** [comment]
I am interested in working on this @ashish-ad if you feel this issue is good to go you can assign me this issue.

**Comment by ashish-ad** [comment]
Ok, @sabyasachi-894 and @Vedant-Jayesh-Oza u both just collaborate within this feature development both can work on this.
I will be assigning u both.

**Comment by sabyasachi-894** [comment]
Sure thanks

**Comment by Vedant-Jayesh-Oza** [comment]
Hey @sabyasachi-894 you can start working on the issue actually I have my one pending issue left to work on.  You can start working on it. If you need help I'll surely help.

**Comment by jay-io** [comment]
I'm ready to collaborate and work on this issue. Can I have it assigned to me as well @ashish-ad ?

**Comment by ashish-ad** [comment]
Yeah sure, @jay-io go ahead!!!

**Comment by ashish-ad** [comment]
Ok I think @sabyasachi-894, Has completed this and he going to make PR on this, if something is left u can collaborate with @jay-io .
