### ISSUE TITLE
Create an Error 404 page for the website

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Gdsc-Lbce/GDSC_LBCE_Website#36]
Hey @ashish-ad , I feel we should add an error 404 page for the website. I you feel the issue is beneficial for the project, please Assign this issue to me under WoC 2.0. Thank You.

**Comment by ashish-ad** [comment]
Yeah, sure...

**Comment by Sauradip07** [comment]
please check my PR #50
