### ISSUE TITLE
add social media links to the banner. 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [Gdsc-Lbce/GDSC_LBCE_Website#43]
* **I'm submitting a ...**
  - [x] bug fix
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Hey @ashish-ad I would like to add the social media links to the banner of the website

* **What is the current behavior?**
When we click on the social media icons in the banner it doesn't re-directs to the social media pages of college LBCE.

* **What is the expected behavior?**
I will be adding the links of the social media accounts of the college so that it redirects to the respective social media page when we click on the icon.

Please assign this issue to me under WoC 2.0

**Comment by ashish-ad** [comment]
ok sure @Vedant-Jayesh-Oza, u can start working on this.

**Comment by Vedant-Jayesh-Oza** [comment]
Okay, Will Start working on this 👍
